[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "1.1.0"
authors = ["Block <ai-oss-tools@block.xyz>"]
license = "Apache-2.0"
repository = "https://github.com/block/goose"
description = "An AI agent"

[workspace.lints.clippy]
uninlined_format_args = "allow"

[workspace.dependencies]
rmcp = { version = "0.4.0", features = ["schemars", "auth"] }

# Patch for Windows cross-compilation issue with crunchy

