[package]
name = "goose-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[[bin]]
name = "goose"
path = "src/main.rs"

[dependencies]
goose = { path = "../goose" }
goose-bench = { path = "../goose-bench" }
goose-mcp = { path = "../goose-mcp" }
mcp-client = { path = "../mcp-client" }
mcp-server = { path = "../mcp-server" }
mcp-core = { path = "../mcp-core" }
rmcp = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
cliclack = "0.3.5"
console = "0.15.8"
dotenvy = "0.15.7"
bat = "0.24.0"
anyhow = { workspace = true }
serde_json = { workspace = true }
jsonschema = "0.30.0"
tokio = { workspace = true }
futures = "0.3"
serde = { workspace = true }  # For serialization
serde_yaml = "0.9"
tempfile = "3"
etcetera = "0.8.0"
rand = "0.8.5"
rustyline = "15.0.0"
tracing = "0.1"
chrono = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json", "time"] }
tracing-appender = "0.2"
once_cell = { workspace = true }
shlex = "1.3.0"
async-trait = { workspace = true }
base64 = { workspace = true }
regex = "1.11.1"
nix = { version = "0.30.1", features = ["process", "signal"] }
tar = "0.4"
# Web server dependencies
axum = { workspace = true }
tower-http = { version = "0.5", features = ["cors", "fs"] }
http = "1.0"
webbrowser = { workspace = true }
indicatif = "0.17.11"
tokio-util = "0.7.15"
is-terminal = "0.4.16"
anstream = "0.6.18"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wincred"] }


[dev-dependencies]
tempfile = "3"
temp-env = { version = "0.3.6", features = ["async_closure"] }
test-case = "3.3"
tokio = { version = "1.43", features = ["rt", "macros"] }
